Base on alpine and support more parameters
mozmeao/cloudflare-datadog pull request #3
Opened 2017-03-11 22:58 UTC by so0k

Changes:

- Use alpine as base
- Add dockerignore and make scripts
- Add Env var to specify analytics range as this depends on CF Plan
- Add Kubernetes deployment (will move to Helm chart soon)

2017-03-12 00:50 UTC, so0k commented
I'm wondering if it wouldn't be better to use [the python-cloudfare package](https://github.com/cloudflare/python-cloudflare).

```bash
pip install python-cloudflare
```

Export env vars
```bash
export CF_API_EMAIL=
export CF_API_KEY=
```

Sample python script

```python
from CloudFlare import CloudFlare
from pprint import pprint

cf = CloudFlare()
zone = cf.zones.get(params={'name':'yourdomain.com'})
dashboard=cf.zones.analytics.dashboard.get(zone[0]['id'],params={'since':'-360'})

len(dashboard['timeseries'])
pprint(dashboard['timeseries'][0])
```

and make some changes to the conversion of the cloudflare response to the datadog timeseries... (I think the only difference is that the requests object has an extra layer to unpack)

The advantage is:

- script no longer needs to map keys from env var
- no need to figure out the zone id in advance

2017-03-12 07:14 UTC, jgmize commented
Thanks @so0k, I haven't had a chance to give this a thorough review yet, but this is looking great to me so far! I'm also really happy to hear that you're planning on making a helm chart later; I've filed #4 to track that.

@glogiotatidis, if you have time to review this in the next couple of days please take a look; I'd love to get this moved over from whichever of our legacy clusters this is currently running on to one of our k8s clusters.

2017-03-14 12:06 UTC, glogiotatidis requested changes
Hi @so0k thanks for the suggestions, additions and the PR! 🍻 

Since this is coming directly from honestbee/master is tuned for your needs. Could you please replacing the custom parts / variables with more generic ones and cleaning it up a bit?

2017-03-14 12:06 UTC, glogiotatidis commented on Dockerfile
> +  && ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
* Why is this needed? 
 * UTC is a more sane default. 
 * We can move the liking part to an `entrypoint` script so it's easy to select timezone via env variables.

2017-03-14 12:06 UTC, glogiotatidis commented on Makefile
> +DOCKER_REGISTRY ?= registry.honestbee.com/
I'd prefer to use docker registry as  the default public registry

2017-03-14 12:06 UTC, glogiotatidis commented on README.md
> +[![Docker Repository on Quay](https://quay.io/repository/honestbee/cloudflare-datadog/status "Docker Repository on Quay")](https://quay.io/repository/honestbee/cloudflare-datadog)
Let's change this to https://hub.docker.com/r/mozmeao/cloudflare-datadog

2017-03-14 12:06 UTC, glogiotatidis commented on Dockerfile
> +RUN apk add --no-cache tzdata \
👍 for `apt --no-cache`

2017-03-14 12:06 UTC, glogiotatidis commented on k8s-bundle.yaml
> +        image: registry.honestbee.com/honestbee/cloudflare-datadog:latest
Update to point to https://hub.docker.com/r/mozmeao/cloudflare-datadog please

2017-03-14 12:06 UTC, glogiotatidis commented on k8s-bundle.yaml
> +      - name: honestbee-registry
And remove this.

2017-03-14 12:06 UTC, glogiotatidis commented on env2secret.py
> +#!/usr/bin/env python
Do you mind getting this file pep8 compatible to keep things tidy?

2017-03-14 14:36 UTC, metadave commented on README.md
> +kubectl apply -f secret.yaml
did we decide upon a namespace to run this in?

2017-03-14 15:59 UTC, so0k commented on Makefile
> +DOCKER_REGISTRY ?= registry.honestbee.com/
I forgot that was in there :) I think the Makefile can be removed all together and just use an automated repository.

2017-03-14 15:59 UTC, so0k commented on Dockerfile
> +  && ln -sf /usr/share/zoneinfo/Asia/Singapore /etc/localtime
Ok, adding env var support for this (entrypoints are the new init scripts)

2017-03-14 16:00 UTC, so0k commented on k8s-bundle.yaml
> +        image: registry.honestbee.com/honestbee/cloudflare-datadog:latest
I think we should drop the k8s-bundle.yaml and refer to the helm chart? (Unless we want to support ppl who don't want to install helm?)

2017-03-14 16:00 UTC, so0k commented on env2secret.py
> +#!/usr/bin/env python
I thought about dropping the Makefile and the need for this file as Helm is much better at handling release on k8s

2017-03-14 16:56 UTC, so0k commented
With the support for Timezone, test as follows:

```shell
$ docker run -it --rm cloudflare-datadog date
Tue Mar 14 16:55:54 UTC 2017
$ docker run -it --rm -e "TIMEZONE=Asia/Singapore" cloudflare-datadog date
Wed Mar 15 00:56:08 SGT 2017
```

List available timezone info:
```shell
$ docker run -it --rm cloudflare-datadog sh -c "apk add --no-cache tree && tree /usr/share/zoneinfo/"
/usr/share/zoneinfo/
├── Africa
│   ├── Abidjan
│   ├── Accra
│   ├── Addis_Ababa
│   ├──...
```

2017-03-15 08:38 UTC, glogiotatidis commented on env2secret.py
> +#!/usr/bin/env python
I agree on dropping the makefile and keeping only Helm. Both our teams are using Helm so lets keep this simple.

2017-03-15 08:38 UTC, glogiotatidis commented
I linked this repository to docker hub as automated build thus we can drop the Makefile and related files.

2017-03-15 08:47 UTC, so0k commented
Makefile can still be handy to test a build locally, I removed all private registry stuff.

2017-03-15 10:48 UTC, glogiotatidis commented
LGTM! I'll squash merge this and work on #5. Thanks again @so0k ⭐️

2017-03-15 10:48 UTC, glogiotatidis approved these changes

2017-03-15 10:49 UTC, merged